CREATE TABLE MARCA (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(100) NOT NULL,
	
	PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(50) NOT NULL,
	
	PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(100) NOT NULL,
	ID_MARCA integer NOT NULL,
	ID_CATEGORIA integer NOT NULL,
	BARRAS varchar(20),
	VLR_CUSTO double NOT NULL,
	VLR_PRECO double NOT NULL,
	QTD_ESTOQUE double,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID)
);

CREATE TABLE CIDADE (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(50) NOT NULL,
	UF char(2) NOT NULL,
	
	PRIMARY KEY (ID)
);

CREATE TABLE TERCEIRO (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(100) NOT NULL,
	CPF varchar(20),
	CNPJ varchar(20),
	ENDERECO varchar(100),
	BAIRRO varchar(100),
	NUMERO integer,
	CIDADE integer,
	TELEFONE varchar(100),
	EMAIL varchar(100),
	
	PRIMARY KEY (ID),
    FOREIGN KEY (CIDADE) REFERENCES CIDADE (ID)
);

CREATE TABLE VENDA (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_CLIENTE integer NOT NULL,
	ID_VENDEDOR integer NOT NULL,
	DATA DATE NOT NULL,
	VLR_TOTAL double NOT NULL,
	
	PRIMARY KEY (ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TERCEIRO (ID),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES TERCEIRO (ID)
);

CREATE TABLE VENDA_PRODUTO (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_VENDA integer NOT NULL,
	ID_PRODUTO integer NOT NULL,
	QUANTIDADE double NOT NULL,
	UNITARIO double NOT NULL,
	DESCONTO double,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_VENDA) REFERENCES VENDA (ID),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);

CREATE TABLE COMPRA (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_FORNECEDOR integer NOT NULL,
	DATA DATE NOT NULL,
	VLR_TOTAL double NOT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_FORNECEDOR) REFERENCES TERCEIRO (ID)
);

CREATE TABLE COMPRA_PRODUTO (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_COMPRA integer NOT NULL,
	ID_PRODUTO integer NOT NULL,
	QUANTIDADE double NOT NULL,
	UNITARIO double NOT NULL,
	DESCONTO double,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);