CREATE TABLE PRODUTO (
	ID serial NOT NULL,
	NOME varchar(100) NOT NULL,
	ID_MARCA integer NOT NULL,
	ID_CATEGORIA integer NOT NULL,
	BARRAS varchar(20),
	VLR_CUSTO double precision NOT NULL,
	VLR_PRECO double precision NOT NULL,
	QTD_ESTOQUE double precision,
	
	CONSTRAINT PRODUTO_pk PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
	ID serial NOT NULL,
	NOME varchar(50) NOT NULL,
	
	CONSTRAINT CATEGORIA_pk PRIMARY KEY (ID)
);

CREATE TABLE TERCEIRO (
	ID serial NOT NULL,
	NOME varchar(100) NOT NULL,
	CPF_CNPJ varchar(20),
	ENDERECO varchar(100),
	BAIRRO varchar(100),
	NUMERO integer,
	ID_CIDADE integer,
	TELEFONE varchar(100),
	EMAIL varchar(100),
	CLIENTE char(1),
	FORNECEDOR char(1),
	VENDEDOR char(1)
	
	CONSTRAINT TERCEIRO_pk PRIMARY KEY (ID)
);

CREATE TABLE CIDADE (
	ID serial NOT NULL,
	NOME varchar(50) NOT NULL,
	UF char(2) NOT NULL,
	
	CONSTRAINT CIDADE_pk PRIMARY KEY (ID)
);

CREATE TABLE COMPRA (
	ID serial NOT NULL,
	ID_FORNECEDOR integer NOT NULL,
	DATA DATE NOT NULL,
	VLR_TOTAL double precision NOT NULL,
	
	CONSTRAINT COMPRA_pk PRIMARY KEY (ID)
);

CREATE TABLE VENDA (
	ID serial NOT NULL,
	ID_CLIENTE integer NOT NULL,
	ID_VENDEDOR integer NOT NULL,
	DATA DATE NOT NULL,
	VLR_TOTAL double precision NOT NULL,
	
	CONSTRAINT VENDA_pk PRIMARY KEY (ID)
);

CREATE TABLE VENDA_PRODUTO (
	ID serial NOT NULL,
	ID_VENDA integer NOT NULL,
	ID_PRODUTO integer NOT NULL,
	QUANTIDADE double precision NOT NULL,
	UNITARIO double precision NOT NULL,
	DESCONTO double precision,
	
	CONSTRAINT VENDA_PRODUTO_pk PRIMARY KEY (ID)
);

CREATE TABLE COMPRA_PRODUTO (
	ID serial NOT NULL,
	ID_COMPRA integer NOT NULL,
	ID_PRODUTO integer NOT NULL,
	QUANTIDADE double precision NOT NULL,
	UNITARIO double precision NOT NULL,
	DESCONTO double precision,
	
	CONSTRAINT COMPRA_PRODUTO_pk PRIMARY KEY (ID)
);

CREATE TABLE MARCA (
	ID serial NOT NULL,
	NOME varchar(100) NOT NULL,
	
	CONSTRAINT MARCA_pk PRIMARY KEY (ID)
);

ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_fk0 FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID);
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_fk1 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID);
ALTER TABLE TERCEIRO ADD CONSTRAINT TERCEIRO_fk0 FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID);
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_fk0 FOREIGN KEY (ID_FORNECEDOR) REFERENCES TERCEIRO(ID);
ALTER TABLE VENDA ADD CONSTRAINT VENDA_fk0 FOREIGN KEY (ID_CLIENTE) REFERENCES TERCEIRO(ID);
ALTER TABLE VENDA ADD CONSTRAINT VENDA_fk1 FOREIGN KEY (ID_VENDEDOR) REFERENCES TERCEIRO(ID);
ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT VENDA_PRODUTO_fk0 FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID);
ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT VENDA_PRODUTO_fk1 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID);
ALTER TABLE COMPRA_PRODUTO ADD CONSTRAINT COMPRA_PRODUTO_fk0 FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID);
ALTER TABLE COMPRA_PRODUTO ADD CONSTRAINT COMPRA_PRODUTO_fk1 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID);